title: EngiNerd's Blog
description: Full Stack Engineer
author: 
  name: Vladimir Loskutov

logo: /assets/images/logo.webp

# JSON-LD
bio:
  gender: male
  employer_name: Axle Informatics
  employer_url: https://axleinfo.com/
  job_title: Full Stack Developer

social-links:
  dribbble:
  email: vladimir@enginerd.io
  facebook:
  flickr:
  github: en9inerd
  instagram:
  linkedin: vloskutov
  pinterest:
  rss: rss # just type anything here for a working RSS icon
  twitter:
  keyoxide: aspe:enginerd.io:VAXYFU5Y2CCDW5XIYLZOVNEMYM
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

social:
  name: Vladimir Loskutov
  links: 
    - https://www.linkedin.com/in/vloskutov
    - https://github.com/en9inerd
    - https://keyoxide.org/aspe:enginerd.io:VAXYFU5Y2CCDW5XIYLZOVNEMYM

contact_form_script_id: AKfycby7x6xohzq6X0KNiW04ZRhrAblqsKfmUIvzstK4UCXUk4RNh2pe1ClwTlZ8EEkgFwDU

monitor: true

giscus:
  repo: en9inerd/en9inerd.github.io
  repo_id: MDEwOlJlcG9zaXRvcnk4NjUwMzI3NQ==
  category: Comments
  category_id: DIC_kwDOBSfva84CdzzY
  mapping: og:title
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  theme: dark
  lang: en
  loading: lazy
  crossorigin: anonymous

pgp-key:
  show: true
  url: https://keys.openpgp.org/vks/v1/by-fingerprint/3A6B30B1C535625D51CAA2F0232A56BCFF4EAEF2
  fingerprint: 3A6B 30B1 C535 625D 51CA A2F0 232A 56BC FF4E AEF2

google_analytics: G-XZRL66P63S

paginate: 5
paginate_path: "/page/:num/"

permalink: pretty

excerpt_separator: <!--more-->

url: https://enginerd.io
baseurl: ""

show_downloads: false
show_forks: true
future: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: false

timezone: America/New_York
lang: en-US

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-paginate

sass:
  style: compressed

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

remote_theme: en9inerd/hacker

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .well-known/aspe/id/VAXYFU5Y2CCDW5XIYLZOVNEMYM
