title: EngiNerd's Blog
description: Software Engineer, former Network Engineer
author: Vladimir Loskutov

logo: /assets/img/logo.jpg

footer-links:
  dribbble:
  email: vladimir@enginerd.io
  facebook:
  flickr:
  github: eng1nerd
  instagram:
  linkedin: vloskutov
  pinterest:
  rss: rss # just type anything here for a working RSS icon
  twitter:
  keybase: en9inerd
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

social:
  name: Vladimir Loskutov
  links: 
    - https://www.linkedin.com/in/vloskutov
    - https://github.com/eng1nerd
    - https://keybase.io/en9inerd

disqus: enginerd

google_analytics: UA-66941010-2

paginate: 5

excerpt_separator: <!--more-->

url: http://enginerd.io
baseurl: ""

show_downloads: false
future: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: false

timezone: America/New_York
lang: en-US

gems:
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-avatar
  - jekyll-github-metadata

sass:
  style: compressed
  sass_dir: hacker/_sass
includes_dir: hacker/_includes
layouts_dir: hacker/_layouts

theme: jekyll-theme-hacker

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - hacker
