# The URL the site will be built for
base_url = "https://enginerd.io/"

# The title of the site
title = "EngiNerd's Blog"

# The description of the site
description = "Full Stack Engineer"

author = "Vladimir Loskutov"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the HTML when building the site
minify_html = false

# Whether to generate an Atom feed
generate_feeds = true

# Taxonomies
taxonomies = [{ name = "tags", render = false }]

theme = "hacker"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"

# Whether to render emojis
render_emoji = true

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = true

[extra]
title_separator = "|" # set as |, -, _, etc

# The path to the logo of the site
logo = "images/logo.png"

# Google Analytics tracking ID
google_analytics = "G-XZRL66P63S"

# Contact form script id that points to google macros (e.g. https://script.google.com/macros/s/<script-identifier>/exec)
contact_form_script_id = "AKfycby7x6xohzq6X0KNiW04ZRhrAblqsKfmUIvzstK4UCXUk4RNh2pe1ClwTlZ8EEkgFwDU"

# Visitor notifier based on IFTTT + Webhooks. Sample here - /assets/js/monitor.js
monitor = true

# Menu items
menu = [
  { url = "/about", name = "About" },
  { url = "/projects", name = "Projects" },
  { url = "/tags", name = "Tags" },
]

language_code = "en-US"

# Enable OpenGraph metadata
opengraph = true

# timezone = "America/New_York"
# timeformat = ""

# The path to cv file if you use cv shortcode
cv_file = "/files/Curriculum_Vitae_VL.pdf"

# provide link to edit page on github
edit_page = true

# Use theme specific tags page based on templates/tags.html and content/pages/tags.md
simplified_tags = true

# Social links
social_links = [
  { platform = "email", user_id = "vladimir@enginerd.io" },
  { platform = "github", user_id = "en9inerd" },
  { platform = "linkedin", user_id = "vloskutov" },
  { platform = "feed", user_id = true },
  { platform = "keyoxide", user_id = "3A6B30B1C535625D51CAA2F0232A56BCFF4EAEF2" },
  { platform = "telegram", user_id = "mall0c" },
  # { platform = "facebook", user_id = "" },
  # { platform = "instagram", user_id = "" },
  # { platform = "pinterest", user_id = "" },
  # { platform = "twitter", user_id = "" },
  # { platform = "stackoverflow", user_id = "" },
  # { platform = "youtube", user_id = "" },
]

# GitHub settings that are used to generate the edit page link
[extra.github]
username = "en9inerd"
repo = "en9inerd.github.io"

# Giscus settings
[extra.giscus]
repo = "en9inerd/en9inerd.github.io"
repo_id = "MDEwOlJlcG9zaXRvcnk4NjUwMzI3NQ=="
category = "Comments"
category_id = "DIC_kwDOBSfva84CdzzY"
mapping = "og:title"
strict = 0
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "dark"
lang = "en"
loading = "lazy"
crossorigin = "anonymous"

# PGP key
[extra.pgp_key]
url = "https://keys.openpgp.org/vks/v1/by-fingerprint/3A6B30B1C535625D51CAA2F0232A56BCFF4EAEF2"
fingerprint = "3A6B 30B1 C535 625D 51CA A2F0 232A 56BC FF4E AEF2"

# JSON-LD metadata
[extra.bio]
gender = "male"
employer_name = "Axle Informatics"
employer_url = "https://axleinfo.com/"
job_title = "Full Stack Developer"
links = [
  "https://github.com/en9inerd",
  "https://linkedin.com/in/vloskutov",
  "https://keyoxide.org/aspe:enginerd.io:VAXYFU5Y2CCDW5XIYLZOVNEMYM",
  "https://t.me/mall0c",
  "https://t.me/enginerd",
]
