on: push
name: CI
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install
        run: bundle install
      - name: Check DNS
        run: bundle exec github-pages health-check
